from PyQt6.QtWidgets import (
    QWidget, QVBoxLayout, QHBoxLayout, QLabel, QLineEdit,
    QPushButton, QComboBox, QGroupBox, QTabWidget, QFormLayout,
    QListWidget, QStackedWidget, QDoubleSpinBox, QSpinBox, QRadioButton, QButtonGroup, QCheckBox,
)
from PyQt6.QtCore import Qt
import pyqtgraph as pg

pg.setConfigOption('background', 'w')
pg.setConfigOption('foreground', 'k')


def _no_wheel(widget):
    """Spin/combo boxes must not react to mouse-wheel scrolling — scrolling a
    panel that happens to be under the cursor should never change a value."""
    widget.wheelEvent = lambda event: event.ignore()


class PaceUI(QWidget):
    def __init__(self):
        super().__init__()
        self.init_ui()

    def init_ui(self):
        self.setWindowTitle("PaceMaker: Druck PACE5000 Controller")
        self.resize(920, 800)
        main_layout = QVBoxLayout(self)

        # Connection group (may be hidden when backend is managed externally)
        self.conn_group = QGroupBox("Connection")
        conn_layout = QHBoxLayout()

        self.conn_type_combo = QComboBox()
        self.conn_type_combo.addItems(["TCP (Ethernet)", "Serial (RS232C)"])
        self.conn_type_combo.setMaximumWidth(160)

        self.ip_input = QLineEdit("192.168.1.100")
        self.ip_input.setMaximumWidth(140)
        self.ip_label = QLabel("IP Address:")
        self.port_input = QLineEdit("5025")
        self.port_input.setMaximumWidth(65)
        self.port_label = QLabel("Port:")

        self.com_port_input = QLineEdit("COM1")
        self.com_port_input.setMaximumWidth(70)
        self.com_port_label = QLabel("COM Port:")
        self.baudrate_input = QLineEdit("9600")
        self.baudrate_input.setMaximumWidth(70)
        self.baudrate_label = QLabel("Baud:")

        self.btn_connect = QPushButton("Connect")
        self.btn_disconnect = QPushButton("Disconnect")
        self.btn_disconnect.setEnabled(False)
        self.status_label = QLabel("Status: Disconnected")
        self.status_label.setStyleSheet("color: gray; font-weight: bold;")
        self.instrument_error_label = QLabel("Last Instrument Error: none")
        self.instrument_error_label.setStyleSheet("color: gray; font-weight: bold;")
        self.effort_status_label = QLabel("Effort: ---")
        self.effort_status_label.setStyleSheet("color: gray; font-weight: bold;")

        conn_layout.addWidget(self.conn_type_combo)
        conn_layout.addSpacing(8)
        conn_layout.addWidget(self.ip_label)
        conn_layout.addWidget(self.ip_input)
        conn_layout.addWidget(self.port_label)
        conn_layout.addWidget(self.port_input)
        conn_layout.addWidget(self.com_port_label)
        conn_layout.addWidget(self.com_port_input)
        conn_layout.addWidget(self.baudrate_label)
        conn_layout.addWidget(self.baudrate_input)
        conn_layout.addWidget(self.btn_connect)
        conn_layout.addWidget(self.btn_disconnect)
        conn_layout.addSpacing(16)
        status_layout = QVBoxLayout()
        status_layout.setSpacing(2)
        status_layout.addWidget(self.status_label)
        status_layout.addWidget(self.instrument_error_label)
        status_layout.addWidget(self.effort_status_label)
        conn_layout.addLayout(status_layout)
        conn_layout.addStretch()
        self.conn_group.setLayout(conn_layout)
        main_layout.addWidget(self.conn_group)

        # Show TCP fields by default, hide serial fields
        self._set_conn_fields_visible(tcp=True)
        self.conn_type_combo.currentIndexChanged.connect(self._on_conn_type_changed)

        # API Server group — standalone-only. Not added to main_layout: it
        # lives in a separate subwindow opened from the "API" menu (see
        # Pace5000Window._setup_api_menu in pace5000_app.py), keeping it out
        # of the way for the majority of users who don't need it. Hidden
        # entirely (the whole "API" menu) when the backend is managed
        # externally (embedded mode, e.g. main.py).
        self.api_group = QGroupBox("PACE5000 API Server")
        api_layout = QHBoxLayout()

        self.api_enable_cb = QCheckBox("Enable")
        self.api_enable_cb.setEnabled(False)  # enabled once connected

        self.api_host_label = QLabel("Host:")
        self.api_host_input = QLineEdit("127.0.0.1")
        self.api_host_input.setMaximumWidth(120)

        self.api_port_label = QLabel("Port:")
        self.api_port_spin = QSpinBox()
        self.api_port_spin.setRange(1, 65535)
        self.api_port_spin.setValue(8765)
        self.api_port_spin.setMaximumWidth(80)
        _no_wheel(self.api_port_spin)

        self.api_key_label = QLabel("API Key:")
        self.api_key_input = QLineEdit()
        self.api_key_input.setReadOnly(True)
        self.api_key_input.setMinimumWidth(220)
        self.btn_api_regenerate = QPushButton("Regenerate")
        self.btn_api_copy = QPushButton("Copy")

        self.api_status_label = QLabel("Stopped")
        self.api_status_label.setStyleSheet("color: gray; font-weight: bold;")

        api_layout.addWidget(self.api_enable_cb)
        api_layout.addSpacing(8)
        api_layout.addWidget(self.api_host_label)
        api_layout.addWidget(self.api_host_input)
        api_layout.addWidget(self.api_port_label)
        api_layout.addWidget(self.api_port_spin)
        api_layout.addWidget(self.api_key_label)
        api_layout.addWidget(self.api_key_input)
        api_layout.addWidget(self.btn_api_regenerate)
        api_layout.addWidget(self.btn_api_copy)
        api_layout.addSpacing(16)
        api_layout.addWidget(self.api_status_label)
        api_layout.addStretch()
        self.api_group.setLayout(api_layout)

        self.tabs = QTabWidget()
        self.tab_main = QWidget()
        self.tab_schedule = QWidget()
        self.tabs.addTab(self.tab_main, "Manual Control")
        self.tabs.addTab(self.tab_schedule, "Scheduled Control")
        main_layout.addWidget(self.tabs)
        self.setup_main_tab()
        self.setup_schedule_tab()

    def _set_conn_fields_visible(self, tcp: bool):
        self.ip_label.setVisible(tcp)
        self.ip_input.setVisible(tcp)
        self.port_label.setVisible(tcp)
        self.port_input.setVisible(tcp)
        self.com_port_label.setVisible(not tcp)
        self.com_port_input.setVisible(not tcp)
        self.baudrate_label.setVisible(not tcp)
        self.baudrate_input.setVisible(not tcp)

    def _on_conn_type_changed(self, index: int):
        self._set_conn_fields_visible(tcp=(index == 0))

    def get_pressure_unit(self) -> str:
        return "MPa" if self.radio_unit_mpa.isChecked() else "Bar"

    def set_pressure_unit_enabled(self, enabled: bool):
        self.radio_unit_mpa.setEnabled(enabled)
        self.radio_unit_bar.setEnabled(enabled)

    def setup_main_tab(self):
        layout = QVBoxLayout(self.tab_main)

        plot_group = QGroupBox("Live Pressure")
        plot_layout = QVBoxLayout()
        self.live_pressure_label = QLabel("Current Pressure:  ---  MPa")
        self.live_pressure_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.live_pressure_label.setStyleSheet("font-size: 22px; color: black;")
        plot_layout.addWidget(self.live_pressure_label)
        self.setpoint_live_label = QLabel("Target Pressure:  ---    Slew Rate:  ---")
        self.setpoint_live_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.setpoint_live_label.setStyleSheet("font-size: 10pt; color: #555;")
        plot_layout.addWidget(self.setpoint_live_label)
        self.source_pressure_label = QLabel("−ve source:  ---    +ve source:  ---")
        self.source_pressure_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.source_pressure_label.setStyleSheet("font-size: 10pt; color: #555;")
        plot_layout.addWidget(self.source_pressure_label)
        self.effort_label = QLabel("Effort:  ---  %")
        self.effort_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.effort_label.setStyleSheet("font-size: 10pt; color: #555;")
        plot_layout.addWidget(self.effort_label)
        self.plot_widget = pg.PlotWidget(title="Pressure vs Time")
        self.plot_widget.setLabel("left", "Pressure (MPa)")
        self.plot_widget.setLabel("bottom", "Time", units="s")
        self.plot_widget.getPlotItem().getAxis('left').enableAutoSIPrefix(False)
        self.plot_widget.getPlotItem().getAxis('bottom').enableAutoSIPrefix(False)
        self.plot_widget.showGrid(x=True, y=True)
        self.plot_curve = self.plot_widget.plot(pen=pg.mkPen("#1a6fc4", width=2))
        self.plot_widget.plotItem.vb.setMouseMode(pg.ViewBox.RectMode)
        self.plot_widget.plotItem.vb.setLimits(xMin=0)
        plot_btn_row = QHBoxLayout()
        self.btn_clear_graph = QPushButton("Clear Graph")
        self.plot_time_window_spinbox = QSpinBox()
        self.plot_time_window_spinbox.setRange(10, 3600)
        self.plot_time_window_spinbox.setValue(300)
        self.plot_time_window_spinbox.setMaximumWidth(135)
        self.plot_time_window_spinbox.setToolTip("Display window: show only the latest N seconds")
        plot_btn_row.addStretch()
        plot_btn_row.addWidget(QLabel("Window:"))
        plot_btn_row.addWidget(self.plot_time_window_spinbox)
        plot_btn_row.addWidget(QLabel("sec"))
        plot_btn_row.addSpacing(16)
        plot_btn_row.addWidget(self.btn_clear_graph)
        plot_layout.addWidget(self.plot_widget)
        plot_layout.addLayout(plot_btn_row)
        plot_group.setLayout(plot_layout)
        layout.addWidget(plot_group)

        ctrl_group = QGroupBox("Control Parameters [Press Enter to apply changes]")
        ctrl_layout = QFormLayout()
        self.radio_measure = QRadioButton("Measure")
        self.radio_control = QRadioButton("Control")
        self.radio_measure.setChecked(True)
        self._mode_button_group = QButtonGroup()
        self._mode_button_group.addButton(self.radio_measure)
        self._mode_button_group.addButton(self.radio_control)
        self.radio_unit_mpa = QRadioButton("MPa")
        self.radio_unit_bar = QRadioButton("Bar")
        self.radio_unit_mpa.setChecked(True)
        self._unit_button_group = QButtonGroup()
        self._unit_button_group.addButton(self.radio_unit_mpa)
        self._unit_button_group.addButton(self.radio_unit_bar)
        self.target_input = QLineEdit()
        self.target_input.setPlaceholderText("Enter target pressure and press ENTER")
        self.target_input.setToolTip("Press Enter to submit target pressure safely")
        self.max_safe_pressure_input = QLineEdit()
        self.max_safe_pressure_input.setPlaceholderText("optional — leave blank for no limit")
        self.max_safe_pressure_input.setToolTip(
            "Soft ceiling for this run (e.g. gasket/diamond safety limit). "
            "Pre-filled from the instrument's control-sensor full-scale on "
            "connect; edit or clear as needed."
        )
        self.instrument_full_scale_label = QLabel("Instrument full-scale: ---")
        self.instrument_full_scale_label.setStyleSheet("color: #777; font-size: 9pt;")
        max_safe_layout = QVBoxLayout()
        max_safe_layout.setSpacing(2)
        max_safe_layout.setContentsMargins(0, 0, 0, 0)
        max_safe_layout.addWidget(self.max_safe_pressure_input)
        max_safe_layout.addWidget(self.instrument_full_scale_label)
        rate_layout = QHBoxLayout()
        self.rate_input = QLineEdit("0.02")
        self.rate_input.setPlaceholderText("Enter rate and press ENTER")
        self.rate_pressure_unit_display = QLineEdit("MPa")
        self.rate_pressure_unit_display.setEnabled(False)
        self.rate_pressure_unit_display.setMaximumWidth(45)
        self.rate_time_combo = QComboBox()
        self.rate_time_combo.addItems(["sec", "min"])
        rate_layout.addWidget(self.rate_input)
        rate_layout.addWidget(self.rate_pressure_unit_display)
        rate_layout.addWidget(QLabel("/"))
        rate_layout.addWidget(self.rate_time_combo)
        self.chk_confirm_before_apply = QCheckBox("Confirm before apply")
        self.chk_confirm_before_apply.setChecked(False)
        mode_row = QHBoxLayout()
        mode_row.addWidget(self.radio_measure)
        mode_row.addWidget(self.radio_control)
        mode_row.addStretch()
        unit_row = QHBoxLayout()
        unit_row.addWidget(self.radio_unit_mpa)
        unit_row.addWidget(self.radio_unit_bar)
        unit_row.addStretch()
        ctrl_layout.addRow("Mode:", mode_row)
        ctrl_layout.addRow("Pressure Unit:", unit_row)
        ctrl_layout.addRow("Target Pressure:", self.target_input)
        ctrl_layout.addRow("Max Safe Pressure:", max_safe_layout)
        ctrl_layout.addRow("Slew Rate:", rate_layout)
        ctrl_layout.addRow("", self.chk_confirm_before_apply)
        ctrl_group.setLayout(ctrl_layout)

        rel_group = QGroupBox("Relative Pressure Change")
        rel_layout = QHBoxLayout()
        self.btn_rel_minus = QPushButton("−")
        self.btn_rel_minus.setMaximumWidth(53)
        self.rel_step_spinbox = QLineEdit("0.1")
        self.rel_step_spinbox.setPlaceholderText("step")
        self.rel_step_spinbox.setMaximumWidth(48)
        self.rel_step_spinbox.setMinimumHeight(32)
        self.btn_rel_plus = QPushButton("+")
        self.btn_rel_plus.setMaximumWidth(53)
        rel_layout.addStretch()
        rel_layout.addWidget(self.btn_rel_minus)
        rel_layout.addWidget(self.rel_step_spinbox)
        rel_layout.addWidget(self.btn_rel_plus)
        rel_layout.addStretch()
        rel_group.setLayout(rel_layout)

        ctrl_rel_row = QHBoxLayout()
        ctrl_rel_row.addWidget(ctrl_group, stretch=3)
        ctrl_rel_row.addWidget(rel_group, stretch=1)
        layout.addLayout(ctrl_rel_row)

        log_group = QGroupBox("Data Logging")
        log_layout = QHBoxLayout()
        self.btn_log_start = QPushButton("● Start Logging")
        self.btn_log_start.setStyleSheet(
            "background-color: #4CAF50; color: white; font-weight: bold; padding: 6px 16px;"
        )
        self.btn_log_start.setEnabled(False)
        self.btn_log_stop = QPushButton("■ Stop / Save Log")
        self.btn_log_stop.setStyleSheet(
            "background-color: #f44336; color: white; font-weight: bold; padding: 6px 16px;"
        )
        self.btn_log_stop.setEnabled(False)
        self.interval_spinbox = QDoubleSpinBox()
        self.interval_spinbox.setRange(0.1, 60.0)
        self.interval_spinbox.setValue(1.0)
        self.interval_spinbox.setSuffix(" s")
        self.interval_spinbox.setDecimals(1)
        self.interval_spinbox.setMaximumWidth(80)
        self.log_status_label = QLabel("Log: Stopped")
        self.log_status_label.setStyleSheet("color: gray; font-weight: bold;")
        self.log_count_label = QLabel("Records: 0")
        self.log_count_label.setStyleSheet("color: gray;")
        log_layout.addWidget(self.btn_log_start)
        log_layout.addWidget(self.btn_log_stop)
        log_layout.addSpacing(16)
        log_layout.addWidget(QLabel("Interval:"))
        log_layout.addWidget(self.interval_spinbox)
        log_layout.addSpacing(16)
        log_layout.addWidget(self.log_status_label)
        log_layout.addWidget(self.log_count_label)
        log_layout.addStretch()
        log_group.setLayout(log_layout)
        layout.addWidget(log_group)

    def setup_schedule_tab(self):
        layout = QVBoxLayout(self.tab_schedule)

        add_group = QGroupBox("Add / Edit Schedule Item")
        add_layout = QVBoxLayout()
        type_row = QHBoxLayout()
        type_row.addWidget(QLabel("Item Type:"))
        self.sched_item_type = QComboBox()
        self.sched_item_type.addItems(["Wait", "Change Pressure"])
        type_row.addWidget(self.sched_item_type)
        type_row.addStretch()
        add_layout.addLayout(type_row)

        self.sched_param_stack = QStackedWidget()

        wait_page = QWidget()
        wait_form = QFormLayout(wait_page)
        self.sched_wait_duration = QLineEdit()
        self.sched_wait_duration.setPlaceholderText("seconds")
        self.sched_wait_duration.setMaximumWidth(120)
        wait_form.addRow("Duration (s):", self.sched_wait_duration)

        pressure_page = QWidget()
        pressure_form = QFormLayout(pressure_page)
        pressure_row = QHBoxLayout()
        self.sched_pressure_input = QLineEdit()
        self.sched_pressure_input.setPlaceholderText("value")
        self.sched_pressure_input.setMaximumWidth(120)
        self.sched_pressure_unit = QComboBox()
        self.sched_pressure_unit.addItems(["MPa", "Bar"])
        pressure_row.addWidget(self.sched_pressure_input)
        pressure_row.addWidget(self.sched_pressure_unit)
        pressure_row.addStretch()
        pressure_form.addRow("Pressure:", pressure_row)
        rate_row = QHBoxLayout()
        self.sched_rate_input = QLineEdit()
        self.sched_rate_input.setPlaceholderText("value")
        self.sched_rate_input.setMaximumWidth(120)
        self.sched_rate_unit = QComboBox()
        self.sched_rate_unit.addItems(["MPa/min", "MPa/sec"])
        rate_row.addWidget(self.sched_rate_input)
        rate_row.addWidget(self.sched_rate_unit)
        rate_row.addStretch()
        pressure_form.addRow("Rate:", rate_row)
        self.sched_param_stack.addWidget(wait_page)
        self.sched_param_stack.addWidget(pressure_page)
        add_layout.addWidget(self.sched_param_stack)

        info_label = QLabel(
            "ℹ A Change Pressure step monitors automatically until the target pressure is reached.\n"
            " You do not need to include settling time in the following Wait step."
        )
        info_label.setStyleSheet(
            "color: #336; font-size: 9pt; background: #eef4ff;"
            "border: 1px solid #aac; border-radius: 4px; padding: 6px;"
        )
        info_label.setWordWrap(True)
        add_layout.addWidget(info_label)

        btn_row = QHBoxLayout()
        self.btn_sched_cancel_edit = QPushButton("✕ Cancel Edit")
        self.btn_sched_cancel_edit.setVisible(False)
        self.btn_sched_add = QPushButton("＋ Add to Schedule")
        btn_row.addStretch()
        btn_row.addWidget(self.btn_sched_cancel_edit)
        btn_row.addWidget(self.btn_sched_add)
        add_layout.addLayout(btn_row)
        add_group.setLayout(add_layout)
        layout.addWidget(add_group)

        table_group = QGroupBox("Schedule")
        table_outer = QVBoxLayout()

        file_btn_row = QHBoxLayout()
        self.btn_sched_save = QPushButton("Save Schedule...")
        self.btn_sched_load = QPushButton("Load Schedule...")
        file_btn_row.addWidget(self.btn_sched_save)
        file_btn_row.addWidget(self.btn_sched_load)
        file_btn_row.addStretch()
        table_outer.addLayout(file_btn_row)

        table_layout = QHBoxLayout()
        self.sched_list = QListWidget()
        table_layout.addWidget(self.sched_list, stretch=1)
        list_btn_col = QVBoxLayout()
        self.btn_sched_up = QPushButton("▲ Up")
        self.btn_sched_down = QPushButton("▼ Down")
        self.btn_sched_edit = QPushButton("✎ Edit")
        self.btn_sched_delete = QPushButton("✕ Delete")
        list_btn_col.addWidget(self.btn_sched_up)
        list_btn_col.addWidget(self.btn_sched_down)
        list_btn_col.addSpacing(8)
        list_btn_col.addWidget(self.btn_sched_edit)
        list_btn_col.addWidget(self.btn_sched_delete)
        list_btn_col.addStretch()
        table_layout.addLayout(list_btn_col)
        table_outer.addLayout(table_layout)
        table_group.setLayout(table_outer)
        layout.addWidget(table_group, stretch=1)

        exec_group = QGroupBox("Logging & Execution")
        exec_layout = QVBoxLayout()
        dir_row = QHBoxLayout()
        dir_row.addWidget(QLabel("Save to:"))
        self.sched_log_dir_display = QLineEdit()
        self.sched_log_dir_display.setReadOnly(True)
        self.sched_log_dir_display.setPlaceholderText(
            "Log save folder (leave blank to choose via dialog on completion)"
        )
        self.btn_sched_browse_dir = QPushButton("Browse...")
        dir_row.addWidget(self.sched_log_dir_display)
        dir_row.addWidget(self.btn_sched_browse_dir)
        exec_layout.addLayout(dir_row)

        ctrl_row = QHBoxLayout()
        self.btn_sched_start = QPushButton("▶ Start Schedule")
        self.btn_sched_start.setStyleSheet(
            "background-color: #4CAF50; color: white; font-weight: bold; padding: 8px 20px;"
        )
        self.btn_sched_stop = QPushButton("■ Stop")
        self.btn_sched_stop.setStyleSheet(
            "background-color: #f44336; color: white; font-weight: bold; padding: 8px 20px;"
        )
        self.btn_sched_stop.setEnabled(False)
        self.sched_status_label = QLabel("Status: Ready")
        self.sched_status_label.setStyleSheet("color: gray; font-weight: bold;")
        self.sched_record_label = QLabel("Records: 0")
        self.sched_record_label.setStyleSheet("color: gray;")
        ctrl_row.addWidget(self.btn_sched_start)
        ctrl_row.addWidget(self.btn_sched_stop)
        ctrl_row.addSpacing(16)
        ctrl_row.addWidget(self.sched_status_label)
        ctrl_row.addStretch()
        ctrl_row.addWidget(self.sched_record_label)
        exec_layout.addLayout(ctrl_row)

        self.sched_warning_label = QLabel("")
        self.sched_warning_label.setStyleSheet(
            "color: #b00; font-weight: bold; background: #fff3cd;"
            "border: 1px solid #f0ad4e; border-radius: 4px; padding: 4px;"
        )
        self.sched_warning_label.setWordWrap(True)
        self.sched_warning_label.setVisible(False)
        exec_layout.addWidget(self.sched_warning_label)
        exec_group.setLayout(exec_layout)
        layout.addWidget(exec_group)
